services:
  postgres:
    image: postgres:16
    container_name: grpc_user_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: grpc_db
    ports:
      - "14432:5432"
    volumes:
      - postgres_data:/var/lib/postresql/postgres_data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: